version: 2
jobs:
  snapshot:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - run: |
          curl \
            --header "Content-Type:application/json" \
            --header "X-Auth-Token:${TOKEN}" \
            --request POST \
            --data '{"project":${GCP_PROJECT},"zones":${GCP_ZONES}}' \
            ${GCP_CF_ENDPOINT}
          echo "Snapshot done"
workflows:
  version: 2
  snapshot-workflow:
    triggers:
      - schedule:
          cron: "30 4 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - snapshot
